use CompanyB;
ALTER TABLE Employees ADD DepartmentName varchar(25);
INSERT INTO Employees.DepartmentName value("IT");
INSERT INTO Employees.DepartmentName value("HR");
INSERT INTO Employees.DepartmentName value("IT");
INSERT INTO Employees.DepartmentName value("Payroll");
INSERT INTO Employees.DepartmentName value("Payroll");
INSERT INTO Employees.DepartmentName value("IT");
INSERT INTO Employees.DepartmentName value("HR");
INSERT INTO Employees.DepartmentName value("IT");
DELETE FROM Employeed WHERE DepartmentID = NULL;
describe Employees;
